export const MOCK_RESOURCES = [
  {
    id: '1',
    name: 'Main Auditorium',
    type: 'LECTURE_HALL',
    capacity: 500,
    location: 'Building A, Floor 1',
    description: 'Large auditorium with state-of-the-art audio/visual equipment.',
    status: 'ACTIVE',
    availableFrom: '08:00',
    availableTo: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    name: 'Advanced Robotics Lab',
    type: 'LAB',
    capacity: 30,
    location: 'Science Wing, Room 302',
    description: 'Equipped with robotic arms and high-performance workstations.',
    status: 'ACTIVE',
    availableFrom: '09:00',
    availableTo: '18:00',
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    name: 'Collaborative Space 1',
    type: 'MEETING_ROOM',
    capacity: 12,
    location: 'Library, Level 2',
    description: 'Perfect for group discussions and project planning.',
    status: 'ACTIVE',
    availableFrom: '07:00',
    availableTo: '23:00',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    name: '4K Projector Unit B',
    type: 'EQUIPMENT',
    capacity: 1,
    location: 'IT Helpdesk',
    description: 'Portable high-resolution projector for presentations.',
    status: 'OUT_OF_SERVICE',
    availableFrom: '08:00',
    availableTo: '17:00',
    imageUrl: 'https://images.unsplash.com/photo-1535016120720-40c646bebb3d?auto=format&fit=crop&q=80&w=800',
  },
];

export const MOCK_BOOKINGS = [
  {
    id: 'b1',
    resourceId: '1',
    userId: 'user-1',
    date: '2026-04-10',
    startTime: '10:00',
    endTime: '12:00',
    purpose: 'Guest Lecture: Future of AI',
    attendees: 350,
    status: 'APPROVED',
    createdAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'b2',
    resourceId: '3',
    userId: 'user-1',
    date: '2026-04-12',
    startTime: '14:00',
    endTime: '16:00',
    purpose: 'Study Group',
    attendees: 8,
    status: 'PENDING',
    createdAt: '2026-04-05T15:30:00Z',
  },
  {
    id: 'b3',
    resourceId: '2',
    userId: 'user-2',
    date: '2026-04-13',
    startTime: '09:00',
    endTime: '11:00',
    purpose: 'Embedded Systems Practical Assessment',
    attendees: 24,
    status: 'PENDING',
    createdAt: '2026-04-06T08:45:00Z',
  },
  {
    id: 'b4',
    resourceId: '1',
    userId: 'user-3',
    date: '2026-04-14',
    startTime: '13:00',
    endTime: '15:00',
    purpose: 'Interfaculty Innovation Forum',
    attendees: 280,
    status: 'REJECTED',
    rejectionReason: 'Conflicts with a pre-approved university event in the same slot.',
    createdAt: '2026-04-06T12:10:00Z',
  },
];

export const MOCK_TICKETS = [
  {
    id: 't1',
    resourceId: '4',
    userId: 'user-1',
    category: 'EQUIPMENT',
    description: 'Projector lamp flickering and turning off randomly.',
    priority: 'HIGH',
    preferredContact: 'student@campus.edu',
    status: 'IN_PROGRESS',
    assignedTo: 'tech-1',
    createdAt: '2026-04-06T09:00:00Z',
  },
  {
    id: 't2',
    resourceId: '2',
    userId: 'user-2',
    category: 'FACILITY',
    description: 'Air conditioning is unstable during afternoon lab sessions.',
    priority: 'MEDIUM',
    preferredContact: 'labassistant@campus.edu',
    status: 'OPEN',
    createdAt: '2026-04-05T13:20:00Z',
  },
  {
    id: 't3',
    resourceId: '1',
    userId: 'user-4',
    category: 'NETWORK',
    description: 'Auditorium presentation network drops during video playback.',
    priority: 'HIGH',
    preferredContact: 'events@campus.edu',
    status: 'OPEN',
    createdAt: '2026-04-07T07:50:00Z',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n1',
    userId: 'user-1',
    type: 'BOOKING_STATUS',
    title: 'Booking Approved',
    message: 'Your booking for Main Auditorium has been approved.',
    relatedEntityId: 'b1',
    isRead: false,
    createdAt: '2026-04-02T11:00:00Z',
  },
  {
    id: 'n2',
    userId: 'user-1',
    type: 'TICKET_STATUS',
    title: 'Technician Assigned',
    message: 'A technician has been assigned to inspect Projector Unit B.',
    relatedEntityId: 't1',
    isRead: false,
    createdAt: '2026-04-06T10:20:00Z',
  },
  {
    id: 'n3',
    userId: 'admin-1',
    type: 'BOOKING_STATUS',
    title: 'Pending Approval Queue',
    message: 'Two new booking requests are waiting for administrative review.',
    relatedEntityId: 'b3',
    isRead: true,
    createdAt: '2026-04-06T12:30:00Z',
  },
  {
    id: 'n4',
    userId: 'tech-1',
    type: 'RESOURCE_STATUS',
    title: 'High Priority Asset Alert',
    message: 'Main Auditorium network stability issue requires technician attention.',
    relatedEntityId: 't3',
    isRead: false,
    createdAt: '2026-04-07T08:10:00Z',
  },
];
