spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smart_campus_operation_hub}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Minhaj#444}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.autosave=conservative
spring.datasource.hikari.data-source-properties.cleanupSavepoints=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
